### ISSUE TITLE
Configuring pino

### ISSUE THREAD

**Issue by karl-run** [atkinchris/next-logger#7]
The log ingestion service I am using have certain requirements that require me to configure pino in a specific way. Is there any way to achieve this?

Great library by the way.

**Comment by atkinchris** [comment]
Unfortunately, this isn't possible at the moment - but it's the next thing I'd like to work on when I get time.

What format would be most useful to you? I was thinking a `.loggerrc.js` file, and a logger construction function `() => (level) => (...log) => void`.

**Comment by rohit-gohri** [comment]
I think best would be to provide a way to pass a pino instance, that would already be configured with transports/serializers/redaction settings/etc. Something like `next-logger.config.js` where we can export a custom logger instance:

```js
// next-logger.config.js
const pino = require('pino');

const logger = pino({
  messageKey: 'message',
  level: process.NODE_ENV === 'production' ? 'info' : 'trace',
  enabled: !(process.env.NO_LOG === 'true'),
});

module.exports = {
	logger,
};
```

**Comment by atkinchris** [comment]
I've got a beta version of this, with config loading - if you wouldn't mind trying it out. I'm especially interested to see how the config loading copes with your Yarn workspaces, @rohit-gohri!

```sh
npm install "https://github.com/atkinchris/next-logger.git#v3.0.0-beta.1"
```

Create a file at the root of your project called `next-logger.config.js` (or feasibly anything else that [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig) can read from). Make this a CommonJS module, and export a field called `logger`. If this is a Pino instance, it will be used instead of the default instance.

For an example, here's the config I've been using this evening on one of my projects that consumes this library.

```js
// next-logger.config.js
const pino = require('pino')

const logger = pino({
  messageKey: 'message',
  timestamp() {
    return `,"@timestamp":"${new Date(Date.now()).toISOString()}"`
  },
  formatters: {
    level(label) {
      return { level: String(label).toUpperCase() }
    },
  },
})

module.exports = {
  logger,
}
```

**Comment by karl-run** [comment]
Nice! That's works perfectly. :) That way I can require that config for my application logger as well.

**Comment by rohit-gohri** [comment]
I somehow missed the original beta release, tested this now. Working great in yarn workspace based monorepo too! 🥳

**Comment by atkinchris** [comment]
Thanks for confirming @karl-run & @rohit-gohri. We've also been using the beta in a couple of production applications since October.

I've formally released this now as a new major version. The existing behaviour is captured in the provided default logger, so there shouldn't be breaking changes.
